홈탭 기본 구조 및 HomeHeaderView, HomeTopMenuView 구현
everymeals/EveryMeal_IOS pull request #5
Opened 2023-08-07 16:41 UTC by haneulKimaa

#4  대학 선택 뷰
closed #4 

### 개발 항목
- color 추가
- 홈탭 기본 구조 구현
- HomeHeaderView, HomeTopMenuView 구현

### 참고사항
- HomeTopMenuView 버튼 레이아웃 수정 필요합니다 🥺

2023-08-07 23:38 UTC, kwangrok92 requested changes
수고하셨습니다 👍

2023-08-07 23:38 UTC, kwangrok92 commented on EveryMeal_iOS/EveryMeal_iOS/Sources/App/Scenes/Home/HomeHeaderView.swift
> +    .padding(.trailing, 20)
.padding(.horizontal, 20) 으로 한줄로 가능한 것 같습니다.

2023-08-07 23:38 UTC, kwangrok92 commented on EveryMeal_iOS/EveryMeal_iOS/Sources/App/Scenes/Home/HomeView.swift
> +    ScrollView(showsIndicators: true) {
네비게이션뷰도 같이 스크롤되어야 하나요?

2023-08-07 23:38 UTC, kwangrok92 commented on EveryMeal_iOS/EveryMeal_iOS/Sources/App/Scenes/Home/HomeTopMenuView.swift
> +    HomeView()
프리뷰는 일부러 전부 다 HomeView로 하신걸까요?

2023-08-07 23:38 UTC, kwangrok92 commented on EveryMeal_iOS/EveryMeal_iOS/Sources/App/Scenes/Home/HomeTopMenuView.swift
> +struct TopMenuButton: View {
TopMenuButtons 라고 복수형으로 해주시면 더 직관적인 네이밍일 것 같습니다.

2023-08-07 23:38 UTC, kwangrok92 commented on EveryMeal_iOS/EveryMeal_iOS/Sources/App/Scenes/Home/HomeTopMenuView.swift
> +    }
pressed 상태에만 grey2 효과를 주고 뗐을 때 clear로 바뀌는 걸로 수정해야할 것 같습니다.

2023-08-08 00:54 UTC, haneulKimaa commented on EveryMeal_iOS/EveryMeal_iOS/Sources/App/Scenes/Home/HomeTopMenuView.swift
> +    HomeView()
@kwangrok92 네네 전체 모습 보면서 하는게 편할 것 같아서 홈뷰로 놓고 작업했습니당

2023-08-08 03:06 UTC, haneulKimaa commented on EveryMeal_iOS/EveryMeal_iOS/Sources/App/Scenes/Home/HomeView.swift
> +    ScrollView(showsIndicators: true) {
@kwangrok92 확인해보겠습니다!

2023-08-08 03:12 UTC, haneulKimaa commented on EveryMeal_iOS/EveryMeal_iOS/Sources/App/Scenes/Home/HomeTopMenuView.swift
> +    }
@kwangrok92 이부분 말씀하신대로 ButtonStyle 사용해서 configuration.isPressed 상태로 받아오는 것으로 했는데 버튼 터치 뗄 때 더 진하게 뭔가 색상이 들어가더라구요! 그래서 
```Swift
struct PressActions: ViewModifier {
  var onPress: () -> Void
  var onRelease: () -> Void
  
  func body(content: Content) -> some View {
    content
      .simultaneousGesture(
        DragGesture(minimumDistance: 0)
          .onChanged({ _ in
            onPress()
          })
          .onEnded({ _ in
            onRelease()
          })
      )
  }
}
```
이런식으로 추가해서 버튼 누를때 뗄때 따로 처리해줬습니다! 추후 개발에 참고 부탁드립니다

2023-08-08 03:13 UTC, ios-kkr commented on EveryMeal_iOS/EveryMeal_iOS/Sources/App/Scenes/Home/HomeTopMenuView.swift
> +    }
오오오오오 감사합니다. 참고하겠습니다.

2023-08-08 03:14 UTC, haneulKimaa commented on EveryMeal_iOS/EveryMeal_iOS/Sources/App/Scenes/Home/HomeView.swift
> +    ScrollView(showsIndicators: true) {
@kwangrok92 요부분 figma에 디자인팀에 질문 요청드렸습니다. 답변받으면 추후 수정하도록 하겠습니다🫡

2023-08-08 03:22 UTC, merged